import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { ConvexClientProvider } from "@/components/providers/convex-client-provider"
import { Footer } from "@/components/footer"
import { Toaster } from "@/components/ui/toaster"
import { SessionProvider } from "next-auth/react"
import { auth } from "@/auth"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Snipts",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={`dark ${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        >
          <main>{children}</main>
          <Toaster />
          <Footer />
        </body>
      </html>
    </SessionProvider>
  )
}
