import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignOutButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs"
import { Button } from "@/components/ui/button"
import { LogOutIcon } from "lucide-react"
import { ConvexClientProvider } from "@/components/providers/convex-client-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Snipts",
  description: "Generated by create next app",
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <ConvexClientProvider>
      <html lang="en">
        <body
          className={`dark ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SignedOut>
            <SignUpButton>
              <Button>Sign up</Button>
            </SignUpButton>
          </SignedOut>
          <SignedIn>
            <UserButton />
            <SignOutButton>
              <Button variant="destructive">
                <LogOutIcon className="size-4" />
                Sign out
              </Button>
            </SignOutButton>
          </SignedIn>
          {children}
        </body>
      </html>
    </ConvexClientProvider>
  )
}

export default RootLayout
